site_name: "Guide d'utilisation et d'administration de CiviCRM"
site_url: http://rtfd.civicrm.org
repo_url: https://github.com/civicrm-french/civicrm-user-guide
site_description: 'Un guide pour les utilisateurs et administrateurs de CiviCRM.'
site_author: 'La communauté de CiviCRM'

theme: readthedocs

pages:
- Accueil: 'index.md'
- Introduction:
    - "Qu'est-ce que CiviCRM ?": 'introduction/what-is-civicrm.md'
    - "Des exemples concrets": 'introduction/real-world-examples.md'
    - "Composants": 'introduction/components.md'
    - 'Extensions': 'introduction/extensions.md'
    - "Qui est la communauté CiviCRM ?": 'introduction/who-is-civicrm.md'
- Préparation:
    - "CiviCRM convient-il à votre organisation ?": 'getting-prepared/is-civicrm-for-you.md'
    - 'Identifier vos besoins': 'getting-prepared/identifying-your-needs.md'
    - "L'essayer": 'getting-prepared/test-it-out.md'
    - "Hébergement": 'getting-prepared/hosting.md'
    - 'Faire la transition': 'getting-prepared/transitioning-to-civicrm.md'
- Configuration initiale:
    - "Installation et paramétrage": 'initial-set-up/installation-and-basic-set-up.md'
    - "Travaux programmés": 'initial-set-up/scheduled-jobs.md'
    - "Personnaliser l'interface utilisateur": 'initial-set-up/customizing-the-user-interface.md'
    - "Autorisations et contrôle d'accès": 'initial-set-up/permissions-and-access-control.md'
    - "Sécurité": 'initial-set-up/security.md'
    - 'CiviCRM System Status': 'initial-set-up/civicrm-system-status.md'
- Configuration avancée:
    - 'Configuration des e-mails': 'advanced-configuration/email-system-configuration.md'
    - 'Enregistrement': 'advanced-configuration/change-logging.md'
- L'interface utilisateur:
    - 'Menu, tableau de bord, indicateurs': 'the-user-interface/menu-dashboard-and-dashlets.md'
    - 'Raccourcis clavier': 'the-user-interface/keyboard-shortcuts.md'
    - 'Recherches': 'the-user-interface/searching.md'
    - 'Restauration des contacts': 'the-user-interface/undelete.md'
- Organiser vos données:
    - 'Aperçu': 'organising-your-data/overview.md'
    - "Comment organiser vos données": 'organising-your-data/mapping-your-data.md'
    - 'Contacts': 'organising-your-data/contacts.md'
    - "Groupes et étiquettes": 'organising-your-data/groups-and-tags.md'
    - 'Groupes dynamiques': 'organising-your-data/smart-groups.md'
    - "Activités": 'organising-your-data/activities.md'
    - 'Relationships': 'organising-your-data/relationships.md'
    - "Créer des champs personnalisés": 'organising-your-data/creating-custom-fields.md'
    - "Les Profils": 'organising-your-data/profiles.md'
- Common workflows:
    - 'Importing Data into CiviCRM': 'common-workflows/importing-data-into-civicrm.md'
    - 'Exporting Your Contacts': 'common-workflows/exporting-your-contacts.md'
    - 'Deduping and Merging': 'common-workflows/deduping-and-merging.md'
    - 'Tokens and mail merge': 'common-workflows/tokens-and-mail-merge.md'
    - 'Postal mail communications': 'common-workflows/postal-mail-communications.md'
    - 'Automating tasks': 'common-workflows/automating-tasks.md'
- Contributions:
    - "Qu'est-ce que CiviContribute?": 'contributions/what-is-civicontribute.md'
    - "Configuration et Concepts clés": 'contributions/key-concepts-and-configurations.md'
    - "Contribution en ligne": 'contributions/online-contributions.md'
    - 'Lévée de fonds manuelle': 'contributions/offline-fundraising.md'
    - 'Entrée manuelle des contributions': 'contributions/manual-entry-of-contributions.md'
    - 'Rechercher des contributions': 'contributions/finding-and-viewing-contributions.md'
    - "Envoi de reçus et lettres de remerciements": 'contributions/manual-receipts-and-thank-yous.md'
    - 'Rapports et analyses': 'contributions/reports-and-analysis.md'
    - "Crédit Indirect": 'contributions/soft-credits.md'
    - 'Page de Campagne Personnelles': 'contributions/personal-campaign-pages.md'
    - 'Accounting Integration': 'contributions/accounting-integration.md'
    - "Processeur de paiement": 'contributions/payment-processors.md'
    - 'Facturation': 'contributions/invoicing.md'
    - 'TVA et taxe de vente': 'contributions/sales-tax-and-vat.md'
    - 'Cadeaux': 'contributions/premiums.md'
    - 'Widgets': 'contributions/widgets.md'
- Pledges:
    - 'What is CiviPledge?': 'pledges/what-is-civipledge.md'
    - 'What you need to know': 'pledges/what-you-need-to-know.md'
    - 'Set-up': 'pledges/set-up.md'
    - 'Everyday tasks': 'pledges/everyday-tasks.md'
    - 'Pledges Reports and Analysis': 'pledges/pledges-reports-and-analysis.md'
- Évènements:
    - "Qu'est-ce que CiviEvent?": 'events/what-is-civievent.md'
    - "Planification et gestion des événements": 'events/event-planning-and-management.md'
    - 'Créer un événement': 'events/creating-an-event.md'
    - 'Online event registration': 'events/online-event-registration.md'
    - "Intégrer un événement sur votre site": 'events/integrating-events-with-your-website.md'
    - 'Manual event registration': 'events/manual-event-registration.md'
    - 'Keeping track of events and participants': 'events/keeping-track-of-events-and-participants.md'
    - 'Complex event fees': 'events/complex-event-fees.md'
    - "Modèle d'événement": 'events/event-templates.md'
    - 'Rapports': 'events/reports.md'
    - "Données personnalisées": 'events/custom-data-for-events.md'
    - "Répéter les Evénements": 'events/repeating-events.md'
- "Adhésions":
    - "Qu'est-ce que CiviMember": 'membership/what-is-civimember.md'
    - "Définition des adhésions": 'membership/defining-memberships.md'
    - "Gestion des adhésions en ligne": 'membership/online-membership-sign-up.md'
    - "Saisie manuelle des adhésions": 'membership/manual-entry-of-memberships.md'
    - "Gestion des tarifs d'adhésions": 'membership/membership-price-sets.md'
    - "Trouver et afficher des adhésions": 'membership/finding-and-viewing-memberships.md'
    - "Rapports sur les adhésions": 'membership/membership-reports.md'
    - 'Renouvellement': 'membership/renewals.md'
    - "Adhésions annulées ou expirées": 'membership/cancelling-and-expiring-memberships.md'
    - "Création d'accès réservés aux membres": 'membership/making-member-only-websites.md'
- Email:
    - "Qu'est-ce que Civimail?": 'email/what-is-civimail.md'
    - 'What You Need To Know': 'email/what-you-need-to-know.md'
    - 'Set-up': 'email/set-up.md'
    - 'Maintaining Healthy Email Lists': 'email/maintaining-healthy-email-lists.md'
    - 'Everyday tasks': 'email/everyday-tasks.md'
    - 'Mass mailings using CiviMail': 'email/mass-mailings-using-civimail.md'
    - 'Using tokens in emails': 'email/using-tokens-in-emails.md'
    - 'Reports and analysis': 'email/reports-and-analysis.md'
    - 'Scheduled reminders': 'email/scheduled-reminders.md'
    - 'CiviMail A/B Testing': 'email/civimail-ab-testing.md'
- SMS (text messaging):
    - 'What is SMS?': 'sms-text-messaging/what-is-sms.md'
    - 'Set-up': 'sms-text-messaging/set-up.md'
    - 'Everyday tasks': 'sms-text-messaging/everyday-tasks.md'
    - 'Reports and Analysis (SMS)': 'sms-text-messaging/reports-and-analysis-sms.md'
- Reporting:
    - 'What is CiviReport?': 'reporting/what-is-civireport.md'
    - 'What You Need To Know': 'reporting/what-you-need-to-know.md'
    - 'Set-up': 'reporting/set-up.md'
    - 'Everyday Tasks': 'reporting/everyday-tasks.md'
- Case management:
    - 'What is CiviCase?': 'case-management/what-is-civicase.md'
    - 'What You Need To Know': 'case-management/what-you-need-to-know.md'
    - 'Set-up': 'case-management/set-up.md'
    - 'Everyday Tasks': 'case-management/everyday-tasks.md'
    - 'Reports and analysis': 'case-management/reports-and-analysis.md'
- Campaign:
    - "Qu'est-ce que Civicampaign?": 'campaign/what-is-civicampaign.md'
    - 'What You Need To Know': 'campaign/what-you-need-to-know.md'
    - 'Set-up': 'campaign/set-up.md'
    - 'Everyday tasks': 'campaign/everyday-tasks.md'
    - 'Reports and analysis': 'campaign/reports-and-analysis.md'
- Survey:
    - 'What is CiviSurvey?': 'survey/what-is-civisurvey.md'
    - 'What You Need To Know': 'survey/what-you-need-to-know.md'
    - 'Set-up': 'survey/set-up.md'
    - 'Everyday Tasks': 'survey/everyday-tasks.md'
    - 'Reports and analysis': 'survey/reports-and-analysis.md'
    - 'What is GOTV (Voter Tracking)?': 'survey/what-is-gotv-voter-tracking.md'
- Petition:
    - 'What is CiviPetition?': 'petition/what-is-civipetition.md'
    - 'What You Need To Know': 'petition/what-you-need-to-know.md'
    - 'Set-up': 'petition/set-up.md'
    - 'Everyday Tasks': 'petition/everyday-tasks.md'
    - 'Reports and analysis': 'petition/reports-and-analysis.md'
- Civic Engagement:
    - 'What is CiviEngage?': 'civic-engagement/what-is-civiengage.md'
    - 'What You Need To Know': 'civic-engagement/what-you-need-to-know.md'
    - 'Set-up': 'civic-engagement/set-up.md'
    - 'Everyday Tasks': 'civic-engagement/everyday-tasks.md'
    - 'Reports and analysis': 'civic-engagement/reports-and-analysis.md'
- Grants:
    - 'What is CiviGrant?': 'grants/what-is-civigrant.md'
    - 'What You Need To Know': 'grants/what-you-need-to-know.md'
    - 'Set-up': 'grants/set-up.md'
    - 'Everyday tasks': 'grants/every-day-tasks.md'
    - 'Reports and analyis': 'grants/reports-and-analysis.md'
- Website integration:
    - 'Choisir votre CMS': 'website-integration/choosing-your-cms.md'
    - 'Integrating with Drupal': 'website-integration/integrating-with-drupal.md'
    - "Intégration avec WordPress": 'website-integration/integrating-with-wordpress.md'
    - "Intégration avec Joomla": 'website-integration/integrating-with-joomla.md'
- La communauté CiviCRM:
    - 'The CiviCRM Community': 'the-civicrm-community/the-civicrm-community.md'
    - 'Bug Reporting': 'the-civicrm-community/bug-reporting.md'
    - 'Régionaliser CiviCRM': 'the-civicrm-community/localising-civicrm.md'
    - 'Contributing to this manual': 'the-civicrm-community/contributing-to-this-manual.md'
- Appendices:
    - 'History of this book': 'appendices/history-of-this-book.md'
    - 'Free Software?': 'appendices/free-software.md'
    - 'Glossary': 'appendices/glossary.md'
    - 'Credits': 'appendices/credits.md'
